concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:
      
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
